OK = "My first console project";
First_name = "Ranbir ";
Last_name = "Kapoor";
a = 10;
b = 5;
add = First_name + Last_name ;
add2 = a + b ;
console.log(OK);
console.log(add);
console.log(add2);
console.log(a);
console.log(b);